FORT = gfortran-12

OPTC = O2

MA48_LIB = 0

algen_dir = ../TOOLIB/ALGEN
chole_dir = ../TOOLIB/CHOLE
digis_dir = ../TOOLIB/DIGIS
fftw3_dir = ../TOOLIB/FFTW3
files_dir = ../TOOLIB/FILES
gplot_dir = ../TOOLIB/GPLOT
intpl_dir = ../TOOLIB/INTPL
least_dir = ../TOOLIB/LEAST
minim_dir = ../TOOLIB/MINIM
msolv_dir = ../TOOLIB/MSOLV
qsort_dir = ../TOOLIB/QSORT
randm_dir = ../TOOLIB/RANDM
splin_dir = ../TOOLIB/SPLIN
tchev_dir = ../TOOLIB/TCHEV
utils_dir = ../TOOLIB/UTILS

asfc2_dir = ../TPGLIB/ASFC2
deriv_dir = ../TPGLIB/DERIV
abbot_dir = ../TPGLIB/ABBOT
morph_dir = ../TPGLIB/MORPH
filtr_dir = ../TPGLIB/FILTR
stats_dir = ../TPGLIB/STATS
aniso_dir = ../TPGLIB/ANISO


