main – CREST
main Program
Arthur Francisco
27 statements
Source File
Uses
data_arch
crest_param
script
Calls
Subroutines
subroutine prg_surf()
Main function…
Read more…
Arguments
None
Source Code
program main
!$ use omp_lib
use script, only : read_job
use crest_param
use data_arch, only : I4, R8
implicit none
!~ call test_logistic()
!~ stop
   call prg_surf
   contains
   subroutine prg_surf()
   !================================================================================================
   !<@note Main function...
   !
   ! - retrieve script (job) file
   ! - read script
   ! - run specific functions associated to a script keyword
   !
   !<@endnote
   !------------------------------------------------------------------------------------------------
   implicit none
      character(len=128) :: arg_prg
      character(len=512) :: job_file
      integer(kind=I4)   :: var_i
      ! String initialisation
      arg_prg  = repeat(' ',len(arg_prg))
      JOB_FILE = repeat(' ',len(JOB_FILE))
      var_i = 1
      call get_command_argument(var_i, arg_prg)       ! argument one: argument string
      if (len_trim(arg_prg) == 0) then                ! if there is no job file, stop
         write(TER,*) 'no job file, stop'
         stop
      else
         job_file = trim(arg_prg)
      endif
      call read_job(job_file)   ! the program executes 'prg_repeat' times
      write(TER,*) 'Program completed'
   return
   endsubroutine prg_surf
endprogram main
Call graph
main calls prg_surf
prg_surf calls read_job
read_job calls get_unit, acf_theo, add_nois, alloc_tabs, apod_acf, apod_sur, calc_acf, calc_ffh, calc_ord, calc_z_f, calc_z_i, def_size, digi_fil, end_loop, end_scri, make_msk, make_scratches, make_tex, nb_procs, plt__acf, read_img, repr_img, save_img, smooth__, spct_sur, sta_loop, sta_scri, sta_theo, stat_sur, sub_surf, surface_analysis, selectcase, str_remove_chars
acf_theo calls ellipse_acf, calc_imp_acf
add_nois calls build_heights, scramble, std_array
apod_acf calls ellipse_acf, apod2
apod_sur calls apod, std_array
calc_acf calls acf_wiener
calc_ffh calls calc_fftw3_real_bwd, calc_fftw3_real_fwd, calc_moments
calc_ord calls init_order, sort_array2
calc_z_f calls build_heights, std_array
calc_z_i calls build_heights, scramble, std_array
digi_fil calls calc_fftw3_real_bwd, calc_fftw3_real_fwd, std_array
end_scri calls end_fftw3
make_tex calls calc_fftw3, calc_moments
nb_procs calls omp_get_num_procs
plt__acf calls get_unit, dir_separator, ellipse_acf, mkdir
read_img calls read_surf
repr_img calls alloc_tabs, surface_analysis, apod, calc_moments, fft_filter, init_scal, acf_wiener, scramble, sort_array2, std_array, write_surf
save_img calls init_scal, write_surf
smooth__ calls fft_filter, std_array
spct_sur calls get_unit, apod_sur, calc_fftw3, trans_corner2center
sta_scri calls random_init
stat_sur calls apod_sur, surface_analysis, acf_wiener, sort_array2, std_array
sub_surf calls calc_moments, end_fftw3, fftw_plan_with_nthreads, init_order, omp_get_max_threads, acf_wiener, build_heights, calc_imp_acf, calc_res_acf, progress_bar_terminal, sort_array2, tab_end_fftw3_real, tab_init_fftw3_real
surface_analysis calls get_unit, abbott_param, calc_median, calc_moments, calcul_asfc_hermite, calcul_normales, ellipse_acf, fft_filter, indice_fractal, multiple_anisotropy, peaks_and_pits_curvatures, acf_wiener, surf_area, topology
acf_wiener calls calc_fftw3_real_bwd, calc_fftw3_real_fwd, trans_corner2center, tab_calc_fftw3_real_bwd, tab_calc_fftw3_real_fwd
build_heights calls sort_array2, std_array, pikaia_skku_solver, profil_theo_trie_1d
calc_imp_acf calls apod2, autocov_impo
pikaia_skku_solver calls init, solve
profil_theo_trie_1d calls std_array