alloc_tabs – CREST
alloc_tabs Subroutine
23 statements
Source File
private subroutine alloc_tabs()
Note
Function that allocates arrays in global variable PARAM
Arguments
None
Called by
Source Code
   subroutine alloc_tabs()
   !================================================================================================
   !<@note Function that allocates arrays in global variable [[PARAM]]
   !<@endnote
   !------------------------------------------------------------------------------------------------
   implicit none
      integer(kind=I4) :: w, h
      w = PARAM%width
      h = PARAM%height
      allocate( PARAM%fhi(1:w, 1:h) )       ; PARAM%fhi(1:w, 1:h) = 0         ! *digital filter*
      allocate( PARAM%imp_acf(1:w, 1:h) )   ; PARAM%imp_acf(1:w, 1:h) = 0     ! *imposed autocorrelation*
      allocate( PARAM%order(1:w * h) )      ; PARAM%order(1:w * h) = 0        ! *vector that stores heights order*
      allocate( PARAM%vect_h(1:w * h) )     ; PARAM%vect_h(1:w * h) = 0       ! *vector used to store the heights that meet the stat moments*
      allocate( PARAM%acf_surf(1:w, 1:h) )  ; PARAM%acf_surf(1:w, 1:h) = 0    ! *calculated autocorrelation*
      allocate( PARAM%surf_copy(1:w, 1:h) ) ; PARAM%surf_copy(1:w, 1:h) = 0   ! *surface array copy*
      allocate( PARAM%surf_LF(1:w, 1:h) )   ; PARAM%surf_LF(1:w, 1:h) = 0     ! *surface low frequencies*
      allocate( PARAM%surf_HF(1:w, 1:h) )   ; PARAM%surf_HF(1:w, 1:h) = 0     ! *surface high frequencies*
   return
   endsubroutine alloc_tabs
Call graph
read_job calls alloc_tabs, repr_img
repr_img calls alloc_tabs
prg_surf calls read_job
main calls prg_surf