autocov_impo – CREST
autocov_impo Function
14 statements
Source File
private function autocov_impo(xi, xj, tau1, tau2, alpha, ang)
Note
Function that returns
Arguments
Type Intent Optional Attributes Name
real(kind=R8), intent(in) :: xi
coordinate
real(kind=R8), intent(in) :: xj
coordinate
real(kind=R8), intent(in) :: tau1
correlation length along
real(kind=R8), intent(in) :: tau2
correlation length along
real(kind=R8), intent(in) :: alpha
log(z) where z is often 0.2
real(kind=R8), intent(in) :: ang
angle (rad)
Return Value real(kind=r8)
Called by
Call graph
calc_imp_acf calls autocov_impo
acf_theo calls calc_imp_acf
sub_surf calls calc_imp_acf
read_job calls acf_theo, sub_surf
prg_surf calls read_job
main calls prg_surf