calc_acf – CREST
calc_acf Subroutine
8 statements
Source File
private subroutine calc_acf()
Note
Function that returns the autocorrelation function of a surface PARAM%acf_surf
Arguments
None
Calls
Called by
Source Code
   subroutine calc_acf()
   !================================================================================================
   !<@note Function that returns the autocorrelation function of a surface PARAM%acf_surf
   !
   !<@endnote
   !------------------------------------------------------------------------------------------------
   implicit none
      integer(kind=I4) :: w, h
      w = PARAM%width
      h = PARAM%height
      call acf_wiener(  tab_in = PARAM%surf(1:w, 1:h),          &  ! IN
                       tab_out = PARAM%acf_surf(1:w, 1:h),      &  ! OUT
                             w = w,                             &  ! IN
                             h = h  )                              ! IN
   return
   endsubroutine calc_acf
Call graph
calc_acf calls acf_wiener
acf_wiener calls calc_fftw3_real_bwd, calc_fftw3_real_fwd, tab_calc_fftw3_real_bwd, tab_calc_fftw3_real_fwd, trans_corner2center
read_job calls calc_acf
prg_surf calls read_job
main calls prg_surf