calculs_skku_generique – CREST
calculs_skku_generique Subroutine
14 statements
Source File
public subroutine calculs_skku_generique(bounds, lg, ssk, sku)
Note
Function that calls the right series generator.
Arguments
Type Intent Optional Attributes Name
real(kind=R8), intent(in), dimension(:) :: bounds
interval limits
integer(kind=I4), intent(in) :: lg
vec size
real(kind=R8), intent(out) :: ssk
theoretical Ssk
real(kind=R8), intent(out) :: sku
theoretical Sku
Calls
Source Code
   subroutine calculs_skku_generique(bounds, lg, ssk, sku)
   !================================================================================================
   !<@note Function that calls the right series generator.
   !<
   !<@endnote
   !------------------------------------------------------------------------------------------------
   implicit none
   real   (kind=R8), intent(in), dimension(:)   :: bounds  !! *interval limits*
   integer(kind=I4), intent(in)                 :: lg      !! *vec size*
   real   (kind=R8), intent(out)                :: ssk     !! *theoretical Ssk*
   real   (kind=R8), intent(out)                :: sku     !! *theoretical Sku*
      select case (PARAM%func_gen)
         case(FCT_TANG) ; call calculs_skku_tan(bounds, lg, ssk, sku)
         case(FCT_EXPO) ; call calculs_skku_exp(bounds, lg, ssk, sku)
      endselect
   return
   endsubroutine calculs_skku_generique
Call graph
calculs_skku_generique calls calculs_skku_exp, calculs_skku_tan
calculs_skku_exp calls add_expo
calculs_skku_tan calls add_tang, tang
add_expo calls expo
add_tang calls tang