cost_func_skku – CREST
cost_func_skku Subroutine
8 statements
Source File
private subroutine cost_func_skku(me, x, f)
Quantify de distance between desired moments and calculated moments
Arguments
Type Intent Optional Attributes Name
class(pikaia_class), intent(inout) :: me
real(kind=R8), intent(in), dimension(:) :: x
real(kind=R8), intent(out) :: f
Calls
Source Code
   subroutine cost_func_skku(me, x, f)
   !! Quantify de distance between desired moments and calculated moments
   implicit none
   class(pikaia_class), intent(inout)               :: me
   real(kind=R8)      , intent(in   ), dimension(:) :: x
   real(kind=R8)      , intent(  out)               :: f
      f = fitness_skku_anal(n = PARAM%nparam, x = x(1:PARAM%nparam) )
   return
   endsubroutine cost_func_skku
Call graph
cost_func_skku calls fitness_skku_anal
fitness_skku_anal calls calculs_skku_exp3, calculs_skku_tan
calculs_skku_tan calls add_tang, tang
add_tang calls tang