expo – CREST
expo Function
16 statements
Source File
private function expo(xi, n, alp, bet, mu, si)
Note
Profile function based on the exponential function
Arguments
Type Intent Optional Attributes Name
real(kind=R8), intent(in) :: xi
abscissa
integer(kind=I4), intent(in) :: n
statistical moment degree, n=3 for sk and n=4 for ku
real(kind=R8), intent(in) :: alp
offset so that points are in [b1,b2]
real(kind=R8), intent(in) :: bet
reduction so that points are in [b1,b2]
real(kind=R8), intent(in) :: mu
numerical mean
real(kind=R8), intent(in) :: si
numerical standard deviation
Return Value real(kind=r8)
Called by
Call graph
add_expo calls expo
calculs_skku_exp calls add_expo
calculs_skku_generique calls calculs_skku_exp
fitness_skku_anal calls calculs_skku_exp
cost_func_skku calls fitness_skku_anal