fitness_skku_anal – CREST
fitness_skku_anal Function
15 statements
Source File
private function fitness_skku_anal(n, x)
Note
Generic cost function: difference between the imposed statistical moments and those obtained. The optimization problem must be turned into a maximization problem (as often in the optimization routines).
The closer cost to 100 the better series.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4), intent(in) :: n
number of unknowns
real(kind=R8), intent(in), dimension(1:n) :: x
vector of unknowns
Return Value real(kind=r8)
Calls
Called by
Call graph
fitness_skku_anal calls calculs_skku_exp, calculs_skku_tan
calculs_skku_exp calls add_expo
calculs_skku_tan calls add_tang, tang
add_expo calls expo
add_tang calls tang
cost_func_skku calls fitness_skku_anal