read_job – CREST
read_job Subroutine
110 statements
Source File
public subroutine read_job(job_file)
Note
Function that reads a script file. Keywords are identified and corresponding actions are triggered.
Arguments
Type Intent Optional Attributes Name
character(len=512), intent(in) :: job_file
job file with macros to execute
Calls
Called by
Source Code
   subroutine read_job(job_file)
   !================================================================================================
   !<@note Function that reads a script file. Keywords are identified and corresponding actions are
   !< triggered.
   !<@endnote
   !------------------------------------------------------------------------------------------------
   implicit none
   character(len=512), intent(in) :: job_file   !! *job file with macros to execute*
      integer  (kind=I4) :: vide
      character(len=512) :: keyword
      logical  (kind=I4) :: first
      ! script file
      call get_unit( JOB )
      open(unit = JOB, file = trim(job_file), status = 'old')
      call check_empty_lines()
      ! witness file
      call get_unit( SPY )
      open(unit = SPY, file = "out/spy.txt", status = 'unknown')
      LINE_READ = 0
      first     = .true. ! determine if calc_z_f has been already used
      ! default function used: the tangent function
      PARAM%func_gen = FCT_TANG
      ! default is 2 bounds when generating profiles
      PARAM%nparam = 2
      PARAM%calc_mstt = .true.
      PARAM%calc_zf = .true.
      ! default cutting plane for correlation lengths
      PARAM%orig_surf%cut = 0.5
      PARAM%curr_surf%cut = 0.5
o:    do
         keyword = repeat( ' ', len(keyword) )
         read(JOB, *, iostat = vide) keyword ; LINE_READ = LINE_READ + 1
         ! remove unwanted characters from keyword
         keyword = str_remove_chars(string = trim(keyword), chars = '- # *')
         write(SPY, '(a6,I4.4,a)') "line: ", LINE_READ, ' ', trim(keyword)
         selectcase( keyword(1:8) )
            case('ACF_THEO')
               ! desired acf
               call acf_theo()
            case('ADD_NOIS')
               ! add noise to current surface
               call add_nois()
            case('ALLOCATE')
               ! allocate tabs in PARAM type
               call alloc_tabs()
            case('ANALYSIS')
               call surface_analysis()
            case('APOD_ACF')
               ! apodize acf
               call apod_acf()
            case('APOD_SUR')
               ! apodize surface
               call apod_sur()
            case('CALC_ACF')
               ! determine the surface acf
               call calc_acf()
            case('CALC_FFH')
               ! deigital filter
               call calc_ffh()
            case('CALC_ORD')
               ! determine height order
               call calc_ord()
            case('CALC_Z_F')
               ! final heights
               call calc_z_f()
            case('CALC_Z_I')
               ! starting heights
               call calc_z_i()
            case('DEF_SIZE')
               ! image size
               call def_size()
            case('DIGI_FIL')
               ! apply digital filter
               call digi_fil()
            case('END_LOOP')
               ! loop end
               call end_loop()
            case('END_SCRI')
               ! close the script reading
               call end_scri()
               exit o
            case('MAKE_MSK')
               ! turn image into mask
               call make_msk()
            case('MAKE_SCR')
               ! make secratches
               call make_scratches()
            case('MAKE_TEX')
               ! build a texture
               call make_tex()
            case('NB_PROCS')
               ! number of threads
               call nb_procs()
            case('PLT__ACF')
               ! print the correlation graphs and/or determine
               ! if the stop criterion is reached.
               call plt__acf()
            case('READ_PRF')
               ! read image
               call read_img()
            case('REPR_IMG')
               ! reproduce image
               call repr_img()
            case('SAVE_ACF')
               ! save the acf surface
               if ( sum( PARAM%imp_acf ) == 0 ) then
                  call save_img( tab = PARAM%acf_surf )     ! IN: real acf
               else
                  call save_img( tab = PARAM%imp_acf )      ! IN: wanted acf
               endif
            case('SAVE_PRF')
               ! save image
               call save_img( tab = PARAM%surf )            ! IN: surface to save
            case('SMOOTH__')
               ! low-pass filter
               call smooth__()
            case('SPCT_SUR')
               ! surface spectrum frequencies
               call spct_sur()
            case('STA_LOOP')
               ! loop start
               call sta_loop()
            case('STA_SCRI')
               ! start script
               call sta_scri()
            case('STA_THEO')
               ! desired stat moments
               call sta_theo()
            case('STAT_SUR')
               ! surface moments as reference
               call stat_sur()
            case('SUB_SURF')
               ! extract the best surface
               call sub_surf()
         endselect
      enddo o
      close(JOB)
   contains
      subroutine check_empty_lines()
         !! Check for empty lines in the script
      implicit none
         do
            read(JOB, '(A)', iostat = vide) keyword
            if (vide < 0) then
               rewind(JOB)
               return
            endif
            if (len_trim(keyword) == 0) stop 'Empty line in script file'
         enddo
      return
      endsubroutine check_empty_lines
   endsubroutine read_job
Call graph
read_job calls get_unit, acf_theo, add_nois, alloc_tabs, apod_acf, apod_sur, calc_acf, calc_ffh, calc_ord, calc_z_f, calc_z_i, def_size, digi_fil, end_loop, end_scri, make_msk, make_scratches, make_tex, nb_procs, plt__acf, read_img, repr_img, save_img, smooth__, spct_sur, sta_loop, sta_scri, sta_theo, stat_sur, sub_surf, surface_analysis, selectcase, str_remove_chars
acf_theo calls ellipse_acf, calc_imp_acf
add_nois calls build_heights, scramble, std_array
apod_acf calls ellipse_acf, apod2
apod_sur calls apod, std_array
calc_acf calls acf_wiener
calc_ffh calls calc_fftw3_real_bwd, calc_fftw3_real_fwd, calc_moments
calc_ord calls init_order, sort_array2
calc_z_f calls build_heights, std_array
calc_z_i calls build_heights, scramble, std_array
digi_fil calls calc_fftw3_real_bwd, calc_fftw3_real_fwd, std_array
end_scri calls end_fftw3
make_tex calls calc_fftw3, calc_moments
nb_procs calls omp_get_num_procs
plt__acf calls get_unit, dir_separator, ellipse_acf, mkdir
read_img calls read_surf
repr_img calls alloc_tabs, surface_analysis, apod, calc_moments, fft_filter, init_scal, acf_wiener, scramble, sort_array2, std_array, write_surf
save_img calls init_scal, write_surf
smooth__ calls fft_filter, std_array
spct_sur calls get_unit, apod_sur, calc_fftw3, trans_corner2center
sta_scri calls random_init
stat_sur calls apod_sur, surface_analysis, acf_wiener, sort_array2, std_array
sub_surf calls calc_moments, end_fftw3, fftw_plan_with_nthreads, init_order, omp_get_max_threads, acf_wiener, build_heights, calc_imp_acf, calc_res_acf, progress_bar_terminal, sort_array2, tab_end_fftw3_real, tab_init_fftw3_real
surface_analysis calls get_unit, abbott_param, calc_median, calc_moments, calcul_asfc_hermite, calcul_normales, ellipse_acf, fft_filter, indice_fractal, multiple_anisotropy, peaks_and_pits_curvatures, acf_wiener, surf_area, topology
acf_wiener calls calc_fftw3_real_bwd, calc_fftw3_real_fwd, trans_corner2center, tab_calc_fftw3_real_bwd, tab_calc_fftw3_real_fwd
build_heights calls sort_array2, std_array, pikaia_skku_solver, profil_theo_trie_1d
calc_imp_acf calls apod2, autocov_impo
pikaia_skku_solver calls init, solve
profil_theo_trie_1d calls std_array
prg_surf calls read_job
main calls prg_surf