sta_theo – CREST
sta_theo Subroutine
7 statements
Source File
private subroutine sta_theo()
Required statistical moments
Arguments
None
Called by
Source Code
   subroutine sta_theo()
      !! Required statistical moments
   implicit none
      read(JOB,*) PARAM%m_end%sk, PARAM%m_end%ku ; LINE_READ = LINE_READ +1 ; write(SPY,*) "line: ", LINE_READ, "m_end ", PARAM%m_end%sk, PARAM%m_end%ku
   return
   endsubroutine sta_theo
Call graph
read_job calls sta_theo
prg_surf calls read_job
main calls prg_surf