tang – CREST
tang Function
13 statements
Source File
private function tang(xi, n, alp, bet, mu, si)
Note
Profile function based on the tangent function
Arguments
Type Intent Optional Attributes Name
real(kind=R8), intent(in) :: xi
abscissa
integer(kind=I4), intent(in) :: n
statistical moment degree, n=3 for sk and n=4 for ku
real(kind=R8), intent(in) :: alp
offset so that points are in [b1,b2]
real(kind=R8), intent(in) :: bet
reduction so that points are in [b1,b2]
real(kind=R8), intent(in) :: mu
numerical mean
real(kind=R8), intent(in) :: si
numerical standard deviation
Return Value real(kind=r8)
Called by
Call graph
add_tang calls tang
calculs_skku_tan calls tang, add_tang
calculs_skku_generique calls calculs_skku_tan
fitness_skku_anal calls calculs_skku_tan
cost_func_skku calls fitness_skku_anal